name: Bob the Builder

on:
  push:
    branches: [master]
env:
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
  MAKEFLAGS: -j2

jobs:
  build:
    # Verify we can build on latest Ubuntu with both gcc and clang
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        run: |
          sudo apt-get install -y tree libnet-dev
      - name: Configure & Build
        run: |
          ./autogen.sh
          ./configure --prefix=/usr CC=${{ matrix.compiler }}
          make V=1 -j5
          make install-strip DESTDIR=/tmp
          tree /tmp/usr
  debian:
    # Verify Debian package building
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        run: |
          apt-get update
          apt-get install -y build-essential autoconf automake libnet-dev \
                             dpkg-dev debhelper devscripts
      - name: Building Debian package
        run: |
          ./autogen.sh
          ./configure
          make package
